### ISSUE TITLE
not found registration 

### ISSUE THREAD

**Issue by universcom** [pellaeon/registration#107]
hi 
i can't found "Enable "Registration" in /settings/apps (Upper left dropdown -> plus sign -> "Disabled")" step in nextcloud 12
please help me

**Comment by yaffeweb** [comment]
I believe those are the steps for Owncloud. In Nextcloud you go to the gear in the top right and click the Apps link. There you can enable it. Nextcloud 12 however already has the app available in the list by default, you just have to click the enable button whereas owncloud you have to add the app to the installation manually and then follow then do the instructions that you are trying (ie. dropdown, disabled, then enable)

**Comment by pellaeon** [comment]
I updated the readme to reflect this, closing this issue.
