### ISSUE TITLE
Admin option to invite users via email

### ISSUE THREAD

**Issue by vlldk** [pellaeon/registration#108]
An option to, as an admin, to enter an email adress to which an invite for signup will be sent to? With that, the admin avoids having to ask each user for a desired username and after that have them change the password?
Furthermore this avoids having the user to invite himself/herself and waiting for admin approval

**Comment by pellaeon** [comment]
This is a duplicate to #37 if I'm not mistaken, please re-open if I was.

**Comment by hex-m** [comment]
I don't think this is a duplicate.

#37 requests a way for users to invite "guest users" that have limited permissions.

I have a server and would like to invite some people to use it. Just creating an account for them feels offensive. Mastodon has a very nice and flexible [invitation system](https://github.com/tootsuite/mastodon/pull/5814) that could be used for inspiration. Something like this would help a lot to enable organic growth of instances.
