### ISSUE TITLE
[0.3.1] Compatibility with ownCloud not given?

### ISSUE THREAD

**Issue by buffcode** [pellaeon/registration#114]
I'm currently refactoring and fixed all TravisCI tests and wondered, whether the plugin is compatible with ownCloud at all, as the following classes are used which do not exist in ownCloud<sup>[1]</sup>, but only in nextCloud:

```
ReflectionException: Class \OCP\AppFramework\OCS\OCSException does not exist
ReflectionException: Class \OCP\AppFramework\OCS\OCSNotFoundException does not exist
```

[1]: https://www.google.de/search?safe=off&hl=de&ei=LBg6WoLjMYeLgAaNyrmoBg&q=owncloud+%22OCSNotFoundException%22+-nextcloud&oq=owncloud+%22OCSNotFoundException%22+-nextcloud

**Comment by buffcode** [comment]
Btw. currently I have a green badge for PHP 5.6 - 7.2 with Nextcloud 11, 12, and master. Any ownCloud test fails due to the classes given above.

**Comment by pellaeon** [comment]
In the past I manually test this plugin with ownCloud and Nextcloud, but I simply don't have the time to test all the releases anymore. TravisCI tests work are also stalled because of time constraints.

Thanks for making things work 🙏
