### ISSUE TITLE
Registration App allows to create new users that with the same email

### ISSUE THREAD

**Issue by cdamken** [pellaeon/registration#125]
@pellaeon 

Registration 0.4.0

I'm using 10.0.7 version and Users that was already created over the registration app and the email exist can create new accounts with the same name without problems:

```
{"reqId":"eNL0sQsJz1nCgehCe6iP","level":0,"time":"2018-02-27T15:06:44+01:00","remoteAddr":"IP.NUMBER","user":"--","app":"core","method":"POST","url":"index.php/apps/registration/","message":"Sent mail to "Array
(
    [USERNAME@hotmail.com] => 
)
" with subject "Verify your cloud.damken.com registration request""}
{"reqId":"TcenCLoIFOEARxGDDsSf","level":1,"time":"2018-02-27T15:07:13+01:00","remoteAddr":"IP.NUMBER","user":"--","app":"admin_audit","method":"POST","url":"index.php/apps/registration/verify/6BHIAB","message":"User USERNAME created by IP IP.NUMBER [CLIENT_IP: IP.NUMBER] [USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36]"}
```

It would be to go back to the old behavior when the message was: "the email already exists"

I don't remember since when did it change that behavior.

Thanks a lot

**Comment by pellaeon** [comment]
Already reported and fixed in 45efd7f

**Comment by pellaeon** [comment]
Will release soon.

**Comment by balduin-kowalski** [comment]
Double e-mailadresses are still possible: https://github.com/pellaeon/registration/issues/131
And the registration with an already existing username causes an error: https://github.com/pellaeon/registration/issues/134
