### ISSUE TITLE
Error: Call to a member function addUser() on null

### ISSUE THREAD

**Issue by allmotti** [pellaeon/registration#126]
When I register I put in my email then this pops up:
Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.

Technical details
Remote Address: [IP]
Request ID: [Request IP]

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:** MYSQL

**PHP version:** Latest

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by pellaeon** [comment]
Please attach all information on the issue template.

**Comment by elsatim** [comment]
Any progress on this, I am having the same issue

**Comment by pellaeon** [comment]
@allmotti @elsatim As I said, Please attach all information on the issue template, you are not providing me with enough information to debug.

**Comment by nasmacs** [comment]
It Seems to be the same issue that affected registration app before Nextcloud 12 Fix in June 2017
Now on Nextcloud 13, the issue came back.

(Nextcloud 12 compatibility #75 - jasonbayton opened this issue on 10 Jun 2017 · 7 comments)

**Comment by pellaeon** [comment]
If the "Registered user group" setting in Registration app specifies a non-existent group, this error will occur. This might be because you specified the group in Registration app and deleted the group from Nextcloud admin interface. (Registration doesn't know that you deleted the group)

In https://github.com/pellaeon/registration/commit/9b2adba6aa40caadbb30d212978eb03ec0b45140 I added a workaround for this condition to let the user still able to register, but not added to the group nor being prompted by an exception like yours. It will also log the error.

The fix will be available when I push out the next release.
