### ISSUE TITLE
Use the same email  from new users

### ISSUE THREAD

**Issue by cdamken** [pellaeon/registration#131]
### Steps to reproduce
1. Register a user with an email
2. Finish the registration and log in and out
3. Register a second user with the same email
4. Finish the registration and log in 

### Expected behavior
The user can't request another account with the same email account

### Actual behavior
The user can create as many accounts as he wants with the same email.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** Mysql

**PHP version:**  7.0

**ownCloud version:** 10.0.7

**Updated from an older ownCloud or fresh install:** yes, since ownCloud 3 

**Where did you install onwCloud from:** Tar Files

**Comment by pellaeon** [comment]
OK, so owncloud changed the way how user email is stored.

Nextcloud: stored as the `settings` app value https://github.com/nextcloud/server/blob/master/lib/private/User/User.php#L162
ownCloud: stored in dedicated field in User entity https://github.com/owncloud/core/blob/master/lib/private/User/Account.php#L56
