### ISSUE TITLE
Log In Now Link Broken If User Already Exists

### ISSUE THREAD

**Issue by yaffeweb** [pellaeon/registration#133]
### Steps to reproduce
1. Click Register on homepage after enabling the App
2. Sign Up with an existing email
3. Get next screen with Error A user has already taken this email, maybe you already have an account? You can `<a href="url/to/website/"> log in now </a>`
### Expected behaviour
A button or link to take you back to the homepage

### Actual behaviour
Printed html code for link instead of functioning Link

### Server configuration
**Operating system**:
Ubuntu 16.0.4 LTS
**Web server:**
Apache2
**Database:**
MYSQL
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
13.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/latest.zip via wget
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - dav: 1.4.6
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - registration: 0.4.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - files_external
  - user_external
  - user_ldap
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
Yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
No commands defined in the ldap namespace
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```

c) ...
```
</details>

**Comment by nasmacs** [comment]
Right, Same Problem

![chrome_2018-04-20_15-53-58](https://user-images.githubusercontent.com/13219190/39054885-1c4f508a-44b3-11e8-923f-641c620a0bef.png)

**Comment by rainerjung** [comment]
This still happens. The text printed on the page comes from the exception message set in registration/service/registrationexception.php. This seems to get HTML escaped when presented to the browser, so eg. the opening "<" becomes a "%lt;" etc. It looks like one should not use HTML in exception messages.

**Comment by mathiasconradt** [comment]
Still happens as of today 27.11.2018 latest version

**Comment by shubhank008** [comment]
Any fix for it yet ?

**Comment by rainerjung** [comment]
Maybe fixed by

https://github.com/pellaeon/registration/commit/2678a133dc2ca0b3d6fd7f278268d72c40cb11f6#diff-ccead5dc0922a43e88a98344ff9dcc89

**Comment by yaffeweb** [comment]
i can confirm that in 15.0.7 the link indeed works when trying to register with an already used email address.


On Apr 29, 2019 at 2:37 PM, <rainerjung<mailto:notifications@github.com>> wrote:


Maybe fixed by

2678a13#diff-ccead5dc0922a43e88a98344ff9dcc89<https://github.com/pellaeon/registration/commit/2678a133dc2ca0b3d6fd7f278268d72c40cb11f6#diff-ccead5dc0922a43e88a98344ff9dcc89>

-

**Comment by pellaeon** [comment]
Fixed.
