### ISSUE TITLE
do not send email to admin

### ISSUE THREAD

**Issue by korny2000** [pellaeon/registration#135]
I use Nextcloud 13.0.1 .
After self registration I receved link to email like this:
..index.php/apps/registration/verify/1X1BXA
but admin did not receved :-(
Admin also do not know that new users waiting to approved...
where is problem?
thank you

**Comment by korny2000** [comment]
hmmm..same problem like:
https://github.com/pellaeon/registration/pull/132

**Comment by pellaeon** [comment]
Closed as duplicate
