### ISSUE TITLE
Admin doesn't get informed about new Users waiting to be confirmed in NC-instance...

### ISSUE THREAD

**Issue by JimmyKater** [pellaeon/registration#138]
... other than via email. 

It would be helpful if there would be an "alert" for admins telling them about a waiting confirmation as well as where to find said user-account waiting within admin-accounts. (it was a struggle finding the waiting account at first - then it got clear - they are waiting under "suspended"/"not active")

**Nextcloud version:** 13.0.2 - 13.0.2.1
**Operating system:** Linux 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l
**Webserver:** Apache/2.4.25 (Raspbian) (fpm-fcgi)
**Database:** mysql 10.1.23

**PHP version:** 7.0.27-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Comment by journeym** [comment]
Same here, doesnt work

**Comment by pellaeon** [comment]
The feature to put new users disabled is implemented by @Neraste , maybe you could take a look?

**Comment by Neraste** [comment]
Yeah, I see what you mean. For my needs, it was enough to just have a mail notification, but it would be nice to have pop-up notification within the interface as well. I have no idea how the Nextcloud admin alert works. Consider also that the alert should be displayed to admins and subadmins (group administrators).

> it was a struggle finding the waiting account at first

For this, the notification mail could have the link to the users management page.

**Comment by mathiasconradt** [comment]
Also, there should be a link in the email that allows the activation throug the admin in one click. 

Another thing is though: As an admin, I cannot even find the pending users/approvals anywhere in the system. Where would they be? I don't see the new user under "users" for example, where I would expect them to be with a disabled flag. But they're not.

**Comment by pellaeon** [comment]
Implemented in #150
