### ISSUE TITLE
Errors when registering new users

### ISSUE THREAD

**Issue by yooyhooh** [pellaeon/registration#144]
Hi,

When I registered the new user (with the email address), it sent me this error message on my web page. I checked the logs and only found the new log generated in "/var/log/apache2/":

- error messages from Registration page:

```
Internal Server Error
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.
Technical details
Remote Address: {{ip}}
Request ID: JpHwTUcVRHNVgo4BJ1Pw
```

- error messages from logs
```
/var/log/apache2/error.log
script '/var/www/html/nextcloud/apps/registration/cron.php' not found or unable to stat
```

**Comment by pellaeon** [comment]
I think there are some settings problem with you installation, `apps/registration/cron.php` is not a valid path. Maybe you misconfigured something.
