### ISSUE TITLE
Communicating with this addon via API

### ISSUE THREAD

**Issue by wrbl606** [pellaeon/registration#149]
Is it possible to communicate with this addon via HTTP requests, from for example JS/Java client? I want to create an registration flow without redirecting user to OwnCloud site.

I found this code in `appinfo/routes.php` file:
```php
'ocs' => [
    ['root' => '/registration', 'name' => 'api#validate', 'url' => '/v1/validate', 'verb' => 'POST'],
    ['root' => '/registration', 'name' => 'api#status', 'url' => '/v1/status', 'verb' => 'POST'],
    ['root' => '/registration', 'name' => 'api#register', 'url' => '/v1/register', 'verb' => 'POST']
]
```

But when I make a call to this endpoints I'm redirected to `/apps/files` path. Are those available only for internal calls?

**Comment by pellaeon** [comment]
Maybe you want to take a look at the documentation of OCS registration API implemented in this app: https://gist.github.com/juliushaertl/5a1d1132e7370b5ad38fbd6da3cae5b8 .

Reopen if you think the explanation is not enough.
