### ISSUE TITLE
A button to resend confirmation mail ?

### ISSUE THREAD

**Issue by ldidry** [pellaeon/registration#16]
When you give an email address already in registration process, you got a message saying that. It could be useful to have a button to resend the registration link, in case the first email didn't reach the user mailbox (accidently deleted, mail server down, such situations).

**Comment by pellaeon** [comment]
This is implemented in 7d6d6c0 , included in version 0.0.7.

**Comment by happyreacer** [comment]
@pellaeon very nice job
