### ISSUE TITLE
admin settings issue

### ISSUE THREAD

**Issue by Ruhylian** [pellaeon/registration#161]
Hi pellaeon,

I've just tried your app ( the master version) on OC 10.0.10.4 and it works just fine, all the emails are send, the link does the job but i found an issue...and it's quite a shame that I couldn't find a way to sort it (not that I'm a programmer myself).

Once the app enabled, the settings ( in top right corner drop menu) for the admin user stop working, all other are just fine, users, info logout all good just settings. 

even stranger is that the settings for the new or existing users are working just perfect, is just the admin that doesn't work... when even i try to get to setting, the web interface return example.co.uk is currently unable to handle this request.
HTTP ERROR 500

any ideas about how I can get around this? is quite annoying, I've been looking for a way register for a while and now that i'm so close is quite frustrating  that i have this small but big issue.

Regards

**Comment by pellaeon** [comment]
Hi, thank you for reporting this, could you attach the log file at the time of error 500?

**Comment by NikhilMunda** [comment]
I am using OC 10.0.10 and facing the same issues. After placing the registration folder in apps, then everything works fine but after logging in setting page don't open. Your module is awsum. Please fix it.
[owncloud.log](https://github.com/pellaeon/registration/files/2808376/owncloud.log)

**Comment by timetofaceit** [comment]
I want to add, that when you delete the lib folder with registrationsettings.php file, everything works, but in logs it says that the registrationsettings.php is missing. Also there is always error with integrity check... It shows that it's missing signatures. @pellaeon

**Comment by timetofaceit** [comment]
Hi there,

Maybe someone has found anything to fix this bug? @pellaeon @NikhilMunda @Ruhylian

**Comment by Ruhylian** [comment]
@timetofaceit yes I did found a way around it but I'm afraid that was by migrating to Nextcloud.

**Comment by timetofaceit** [comment]
Hey, 

I have just tested it and it works, thanks @pellaeon . Also, is this app going to be approved?
