### ISSUE TITLE
Log In Now link broken (if user exists)

### ISSUE THREAD

**Issue by shubhank008** [pellaeon/registration#166]
### Steps to reproduce
1. Click Register on homepage after enabling the App
2. Sign Up with an existing email
3. Get next screen with Error A user has already taken this email, maybe you already have an account? You can `<a href="url/to/website/"> log in now </a>`

### Expected behaviour
A button or link to take you back to the homepage

### Actual behaviour
Printed html code for link instead of functioning Link
The text printed on the page comes from the exception message set in registration/service/registrationexception.php. This seems to get HTML escaped when presented to the browser, so eg. the opening "<" becomes a "%lt;" etc. It looks like one should not use HTML in exception messages.

### Server configuration
**Operating system**:
Ubuntu 18.0.4 LTS
**Web server:**
Apache2
**Database:**
MYSQL
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
15
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/latest.zip via wget
**Signing status:**

Signing status
**The content of config/config.php:**

Config report
**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
Yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by pellaeon** [comment]
duplicate as #133
