### ISSUE TITLE
After installing the app, settings page went down

### ISSUE THREAD

**Issue by timetofaceit** [pellaeon/registration#168]
Hi there,

After installing the application, my owncloud settings are no longer accessible... I get this error:

679 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class OCA\Registration\Settings\RegistrationSettings contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (OCP\Settings\ISettings::getPanel, OCP\Settings\ISettings::getSectionID) in /raid/raid1/owncloud/apps/registration/lib/Settings/RegistrationSettings.php on line 9"

Does anyone have any ideas?

**Comment by timetofaceit** [comment]
@pellaeon can you help me with this?

**Comment by pellaeon** [comment]
Please file the issue according to the issue template https://github.com/pellaeon/registration/blob/master/issue_template.md

**Comment by timetofaceit** [comment]
@pellaeon thx for the answer. Here's what I got:

**Expected behavior**

When I open settings in owncloud meniu, it should open settings meniu.

**Actual behavior**

Shows page not found.

**Server configuration**

**Operating system:** Raspbian.

**Web server:** Nginx.

**PHP version:** 7.2.

**Client configuration**

**Browser:** Chrome.

**Operating system:** Windows 10.

**Logs**

**Web server log:**

679 FastCGI sent in stderr: "PHP message: PHP Fatal error: Class OCA\Registration\Settings\RegistrationSettings contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (OCP\Settings\ISettings::getPanel, OCP\Settings\ISettings::getSectionID) in /raid/raid1/owncloud/apps/registration/lib/Settings/RegistrationSettings.php on line 9"

**OwnCloud log:**

679 FastCGI sent in stderr: "PHP message: PHP Fatal error: Class OCA\Registration\Settings\RegistrationSettings contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (OCP\Settings\ISettings::getPanel, OCP\Settings\ISettings::getSectionID) in /raid/raid1/owncloud/apps/registration/lib/Settings/RegistrationSettings.php on line 9"

Do you need anything else?

**Comment by timetofaceit** [comment]
@pellaeon any thoughts about this problem?

**Comment by pellaeon** [comment]
duplicate with #161
