### ISSUE TITLE
Nextcloud 16 support

### ISSUE THREAD

**Issue by PxSonny** [pellaeon/registration#177]
Hi, 

I accidentally upgraded to Nextcloud 16 and lose your plugin, because it appears to not be supported by Nextcloud 16. 

Is it just a matter of upgrading your list of supported versions internally and it's safe to activate the plugin even if Nextcloud 16 tells me it's not compatible? Or is it more subtle and I should probably wait anyhow for the official support for 16?

Thanks a lot. 
Great plugin.

**Comment by pellaeon** [comment]
Should work if you just bump the number. I will update in the weekend.

Sonny Alves Dias <notifications@github.com> 於 2019年5月16日 週四 12:21 寫道：

**Comment by PxSonny** [comment]
Okay great thanks.
