### ISSUE TITLE
Increase email verification token length

### ISSUE THREAD

**Issue by leonklingele-work** [pellaeon/registration#179]
Currently the email verification token is only 6 characters long with a dictionary size of only 36: https://github.com/pellaeon/registration/blob/02f9b632d2b7074b6eb5e83d62c931d791238489/db/registrationmapper.php#L88

Following the birthday paradoxon there will be token collisions with a probability of 50% when there are ~55.000 open registrations: https://play.golang.org/p/zVLvfc2VfSI

Please increase the token length to 10 and increase the dictionary size to 62 by also allowing lowercase characters.

**Comment by pellaeon** [comment]
Fixed
