### ISSUE TITLE
Non html registration email

### ISSUE THREAD

**Issue by pierreozoux** [pellaeon/registration#18]
I don't have an html email client and I couldn't read the mail.

Would be cool to be able to read it from non html email client :)

Thanks!

**Comment by cdamken** [comment]
You probably could modify the following lines:
https://github.com/pellaeon/registration/blob/master/templates/email.php#L2-L3

**Comment by pellaeon** [comment]
I know, but if I revert it to plain text, mail clients **with** HTML support will not be able to simply click the link to open it. So I'd rather keep the current HTML email.

**Comment by cdamken** [comment]
Probably the solution could be: http://kevinjmcmahon.net/articles/22/html-and-plain-text-multipart-email-/

**Comment by pellaeon** [comment]
Implemented in 6865cfd9d0e26ed387ae3dfb787cd312183df389 , will be released in the next version.
