### ISSUE TITLE
Disappeared! Authorised domains within admin area cannot be defined anymore

### ISSUE THREAD

**Issue by 1nv3st1gat0r** [pellaeon/registration#186]
Hi all!

The registration app (NextCloud) is really great and after installing it I already defined the domains that are allowed to register (_-> settings -> additional settings_). And it worked very well. (The only thing I did, was configuring the backend, that the domains that are allowed are not shown if someone tries to register.)

**And suddenly the box administration part of the registration app within "additional settings" disappeared** - and I don't know why. I did a reset, I updated the NextCloud instance to 15.0.10 with an underlying Linux server (Proxmox) with the following installed Apps (next to the Registration App: Accessibility, Activity, AppOrder, Auditing/Logging, Brute-force settings, Collaborative tags, Comments, Deleted files, Federation, File sharing, Log Reader, Monitoring, Nextcloud announcements, Notifications, Password policy, PDF viewer, Right click, Share by mail, SharRenamer, Support, Text editor, Theming, User and Group SQL Backends, Versions, W2G2);

I am not happy with contacting always our administrator for adding new domains for our NextCloud server ... 
Thanks for helping in advance, 
Christina

**Comment by pellaeon** [comment]
Is this still happening? if so, please reopen and follow the issue template.
