### ISSUE TITLE
How can i deactivate the screen "Registration is only allowed for the following domains: "

### ISSUE THREAD

**Issue by F3000** [pellaeon/registration#188]
Hi , 

is it possible to deactivate this screen ? So a user who is not allowed to register, cant see which domains are allowed. 

![Unbenannt](https://user-images.githubusercontent.com/8161283/70434192-d84a3000-1a83-11ea-98da-95e83234ef09.png)

**Comment by anemanic** [comment]
Yes, this is major, please enable possibility to hide list of domains.

**Comment by pellaeon** [comment]
I'll list this as an enhancement, pull requests welcome.

**Comment by pellaeon** [comment]
Duplicate of #119
