### ISSUE TITLE
How can i change email templates ?

### ISSUE THREAD

**Issue by F3000** [pellaeon/registration#189]
See title. 

There are some not correctly translated phrases in the mails.....

**Comment by splitt3r** [comment]
Templates: https://github.com/pellaeon/registration/tree/master/templates
Translations: https://github.com/pellaeon/registration/tree/master/l10n (Crowding seems to be inactive)

**Comment by F3000** [comment]
@splitt3r thanks . When I edit the code in the current installation there is no effect

**Comment by pellaeon** [comment]
The current question is answered, closing this issue.
