### ISSUE TITLE
Registry button is not in the middle

### ISSUE THREAD

**Issue by hensephil** [pellaeon/registration#191]
The registry button on my nextcloud is not in the middle Its slightly to thr left. but its only on the web version of it.
It first started to apear in version 18.0.0.
<img width="691" alt="2020-01-21 14_38_14-Juze" src="https://user-images.githubusercontent.com/51832284/72809370-c4d1dd80-3c5b-11ea-8de2-7a55e8d8ada7.png">

**Comment by krombel** [comment]
I can second that for 18.0.0.
As you can see in the screen shot the design from theming is not applied in general. Else the coloring for the register button should be different.

**Comment by pellaeon** [comment]
Seems that this is a problem from the Nextcloud core stylesheets, which is fixed here: https://github.com/nextcloud/server/pull/19238

Please test, or wait for the next server release.
