### ISSUE TITLE
Nice Idea

### ISSUE THREAD

**Issue by Darksloan** [pellaeon/registration#192]
Hi Guys, it would be nice to have something like an authorization-code maybe like an one time use authorization-code, what you could give to people who want´s to register for your Nextcloud. That not everybody is allowed to register on your nextcloud.

Sorry if I post this in the wrong place, I´m new here so just tell me where i should put it if it´s wrong.

**Comment by pellaeon** [comment]
Nextcloud already has a feature to directly add users by admins. What you're suggesting is too similar to this existing feature, so I will not implement this.
