### ISSUE TITLE
Manage Storage Plan

### ISSUE THREAD

**Issue by trymeouteh** [pellaeon/registration#196]
Is there a way to allow users to signup, and go into their settings to choose a storage plan and pay for more storage? Essentially you will have a default free storage plan which could be like 2GB, then have options like 50GB for $5/month or $50/year, 100GB for $10/month or $100/year, etc.

And allow people to be directed to a payment page or allow the ability to integrate payment processors.

**Comment by acs-ferreira** [comment]
Well, this is an entire module and **commercial features** you must develop and maintain. You should hire a developer for this. Also see https://docs.nextcloud.com/server/latest/developer_manual/

**Comment by pellaeon** [comment]
I agree with @acs-ferreira .
