### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by yooyhooh** [pellaeon/registration#204]
**Internal Server Error**
---------------------------

Problem description: 

When clicking "Request Verification Link", the server replies me with the following errors:

```
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Technical details
Remote Address: <SERVER-Ip>
Request ID: vPJ8p95ljrn8OUBPM0wX
```

**Comment by yooyhooh** [comment]
correction:
`
Remote Address: <client-ip>
`

**Comment by pellaeon** [comment]
Please follow the issue template.
