### ISSUE TITLE
Unable to confirm the email adress

### ISSUE THREAD

**Issue by tadoopai** [pellaeon/registration#208]
IMPORTANT: I use a reverse Proxy ant thats the reason why nextcloud (or the registration plugin) thinks that my (external)ip is the private ip.

 
### Steps to reproduce
1. create a new user
2. send email verification

### Expected behaviour
Email Verification Link with my domain adress (cloud.mydomain.net/[verification link])

### Actual behaviour
Email Verification Link with my private ip adress (private ip/[verification link])

### Server configuration
**Operatin System**: Linux 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64

**Web server: **Apache/2.4.41 (Ubuntu) (apache2handler)

**Database: mysql 5.7.30**mysql 5.7.30

**PHP version:** 7.3.18-1+ubuntu20.04.1+deb.sury.org+1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache**

**Nextcloud version:** 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from: **official website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - analytics: 2.3.1
 - apporder: 0.9.0
 - audioplayer: 2.10.0
 - audioplayer_editor: 0.2.2
 - audioplayer_sonos: 1.1.1
 - auto_groups: 1.2.0
 - bookmarks: 3.0.13
 - breezedark: 18.0.16
 - browser_warning: 0.2.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - camerarawpreviews: 0.7.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dashboardcharts: 0.1.3
 - data_request: 1.5.0
 - dav: 1.14.0
 - dicomviewer: 1.2.2
 - encryption: 2.6.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_antivirus: 2.4.1
 - files_automatedtagging: 1.8.2
 - files_downloadactivity: 1.7.0
 - files_external: 1.9.0
 - files_fulltextsearch: 1.4.2
 - files_fulltextsearch_tesseract: 1.4.1
 - files_linkeditor: 1.0.14
 - files_pdfviewer: 1.7.0
 - files_photospheres: 1.0.8
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - flowupload: 0.1.8
 - fulltextsearch: 1.4.1
 - fulltextsearch_elasticsearch: 1.5.1
 - groupfolders: 6.0.6
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.3.5
 - nextcloud_announcements: 1.7.0
 - notes: 3.3.1
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - quota_warning: 1.7.0
 - recommendations: 0.6.0
 - registration: 0.4.7
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - side_menu: 1.7.0
 - sociallogin: 2.4.6
 - socialsharing_diaspora: 2.0.0
 - socialsharing_email: 2.0.0
 - socialsharing_facebook: 2.0.0
 - socialsharing_twitter: 2.0.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - terms_of_service: 1.4.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - user_usage_report: 1.2.0
 - video_converter: 0.1.4
 - viewer: 1.2.0
 - w2g2: 3.0.1
 - workflow_pdf_converter: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - spreed
 - user_ldap

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.178.31",
            "cloud.[mydomain].net" --> I have removed this here (not in the original file)
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "http:\/\/[mydomain].net", --> I have removed this here (not in the original file)
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "bookmarks_fulltextsearch"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpport": "465",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** yes --> No mounts configured

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** yes OC\User\Database

**Browser: Firefox, Google Chrome**

**Operating system: Windows 10**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
idk I cant copy It but I cant find errors (sorry here too)

But it says: PHP:  
syntax error, unexpected END_OF_LINE, expecting '=' in /etc/php/7.3/apache2/php.ini on line 2
and:
[Thu May 21 12:12:33.176004 2020] [php7:error] [pid 17433] [client 192.168.178.21:50994] PHP Fatal error:  Allowed memory size of 134217728 bytes exh>
[Thu May 21 12:12:58.019462 2020] [php7:error] [pid 17533] [client 192.168.178.21:51070] PHP Fatal error:  Cannot declare class OCA\\Talk\\Migration\>

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
idk I cant copy It but I cant find errors
```
</details>

**Comment by pellaeon** [comment]
This app uses Nextcloud's API `URLGenerator->getAbsoluteURL()` to generate the link. So if the URL is wrong it is likely you misconfigured it.

getAbsoluteURL() will in turn call getServerHost(), which is defined in `nextcloud/lib/private/AppFramework/Http/Request.php`. By looking at the code, it says that it will use the first trusted domain (set in your config.php). So to solve the issue, probably you can try putting your domain address as the first in `trusted_domains`.

**Comment by Bschalck** [comment]
Hy,

I had the same mistakes.

> So to solve the issue, probably you can try putting your domain address as the first in trusted_domains.

That resolves the problem. But It should be nice to have some logs into nextcloud.log when a mail is sent from registration app :)

**Comment by pellaeon** [comment]
I think this should be Nextcloud core's problem, I suggest you open an issue there.
Closing the issue for now.
