### ISSUE TITLE
Admin email notification about registrations

### ISSUE THREAD

**Issue by tobiasnix** [pellaeon/registration#21]
It would be great to have a notification email for admins about new registrations.

**Comment by tobiasnix** [comment]
I just posted a $5 bounty on Bountysource! https://www.bountysource.com/issues/25853133-admin-email-notification-about-registrations

**Comment by pellaeon** [comment]
This is implemented in 7d6d6c068efc4fa3b45e12d40ebdda00dc40aa07 , included in version 0.0.7.

**Comment by pellaeon** [comment]
I'm sorry, I closed the wrong issue :-p

**Comment by pellaeon** [comment]
@tobiasnix You can deny the claim on bountysource.

**Comment by pellaeon** [comment]
Maybe also push a notification to Notification app (https://github.com/owncloud/notifications)

**Comment by tobiasnix** [comment]
That sounds like the better idea. Notification system will then be responsible for mail (if configured). Also it should be displayed on activity stream page.

**Comment by cdamken** [comment]
I'm agree with @tobiasnix, , just after the user is finally registered it could be sent an email to the administration that way he can know.

**Comment by nicoschtein** [comment]
I just saw the bounty and was about to do this but it looks like this has been implemented already https://github.com/pellaeon/registration/commit/d38dd3874d1baf97b4a0d169470bc561489c5765

**Comment by pellaeon** [comment]
Yes, it is already implemented.

2016-05-22 6:05 GMT+08:00 nicoschtein <notifications@github.com>:

**Comment by happicamper** [comment]
How can I activate this feature? It seems that when I successfully created an account logged it doesn't save the email address I put when verifying the email address.

**Comment by yaffeweb** [comment]
I'm also not getting emails when new users register. I can't find anywhere to to even turn this on or off. I believe it is implemented but I can't find anywhere to adjust settings to who it should even send an email notification to. Running nextcloud 12.0.4. Any direction you can point me in would be awesome.

**Comment by cdamken** [comment]
> BTW, I just forced the application to run on ownCloud 10.0.2 version.

the latest version works with 10.0.X without forcing it.

**Comment by pellaeon** [comment]
@yaffeweb Please [make sure your instance can send emails correctly](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/email_configuration.html). If you believe your settings are correct, please check the logs and post relevant lines.

**Comment by pellaeon** [comment]
Closing the issue since it's already implemented.

**Comment by yaffeweb** [comment]
My issue is resolved however I had to completely uninstall and reinstall for it work. Don't know what the hiccup was but Registration Emails are functioning properly now.
