### ISSUE TITLE
Add the user email in the admin notification email

### ISSUE THREAD

**Issue by nlewo** [pellaeon/registration#211]
When a user asks for registration, admin users receive a notification with the following subject:
```
A new user "a-new-username" has created an account on my-nextcloud and awaits admin approbation
```

I would like to have the user email in this message, which would then become:
```
A new user "a-new-username" (a-new-username@example.com) has created an account on my-nextcloud and awaits admin approbation
```  

Would you accept a patch adding the user email in the admin notification email subject?

**Comment by pellaeon** [comment]
Sounds like a useful addition, I would happily accept the patch.
