### ISSUE TITLE
Perform "allowed domains check" earlier..

### ISSUE THREAD

**Issue by valueerrorx** [pellaeon/registration#23]
not after entering the emailadress...   i would prefer to get informed when clicking on "register" or even better..  the button should not show up at all (maybe optional)

thx !

**Comment by pellaeon** [comment]
I don't understand, can you list your desired registration flow by 1, 2, 3, etc. ?

**Comment by valueerrorx** [comment]
well.. sorry..  i openend this issue before i realised that you implemented an "email-domain-check"
This of course can only be done AFTER you enter the emailadress..  i thought you implemented some sort of "origin-check"  - i mean a check against the users IP adress... (because that's what i need in my school..  i want to be able to restrict registration to -inside- the school intranet..  10.* )

In that case (and only in that case) owncloud could perform the check even earlier and not show the registration link at all..  so i guess you can close/delete this issue.

thx !
