### ISSUE TITLE
Support PostgreSQL

### ISSUE THREAD

**Issue by wupdiwup** [pellaeon/registration#24]
You mentioned explicitly this is only compatible with MariaDB. Didn't you verify PgSQL
compatibility or did you ran in concrete problems, if so which? I would be happy to try
making this PgSQL compatible as all my services share a big Postgres cluster and I
don't fancy spinning up a MariaDB just for one service.

**Comment by pellaeon** [comment]
I did not verify PostgreSQL compatibility, you could try, though, tell me the result so I can make it work. :-)

**Comment by jodumont** [comment]
I confirm, when you try to activate App "Registration" with pgsql you receive this message :
App "Registration" cannot be installed because the following dependencies are not fulfilled: Following databases are supported: sqlite, mysql

**Comment by Gnienfo** [comment]
FYI:
I have a nextcloud 11 with postgresql 9.4.
I also tried to add the app and had the same message as @jodumont.

I modified the apps/registration/appinfo/info.xml file to add the line `<database>pgsql</database>` in the `<dependencies>` section.

- activated the app, this time its ok
- tried to create a new user through the new register button on the login page
- entered a mail 
- received a validation link on this mail => clic on it
- entered the new user login/pwd
=> login ok!

So it seams to be compatible with posthresql...

P.S.: sorry for my poor english...

**Comment by rodrigoesborges** [comment]
I had this error when trying to activate the app:
An exception occurred while executing 'ALTER TABLE oc_registration ADD "username" VARCHAR(255) NOT NULL': SQLSTATE[23502]: Not null violation: 7 ERRO: column "username" contains null values

**Comment by pellaeon** [comment]
@juliushaertl Any idea on this?

**Comment by juliushaertl** [comment]
Seems like the error is caused by the same reason as #92

**Comment by rodrigoesborges** [comment]
Thanks @pellaeon  and @juliushaertl I just dropped the oc_registration table and it did the trick.
