### ISSUE TITLE
The username is already being used

### ISSUE THREAD

**Issue by ecostaalfaia** [pellaeon/registration#25]
Hi guys,
I have installed your app in my owncloud, but I am getting this error when I try registering an user.

"The username is already being used" 

I have verified and the user not exist in my database.

Thanks

**Comment by pellaeon** [comment]
Please provide owncloud log of the time you are registering.

**Comment by cdamken** [comment]
could be related to step 5 in https://github.com/pellaeon/registration/issues/26#issuecomment-147424149

**Comment by yavama** [comment]
@ecostaalfaia how did you install the app 
it doesn't work for me
