### ISSUE TITLE
"Enable only for specific groups" is not working

### ISSUE THREAD

**Issue by cookie00** [pellaeon/registration#27]
Hello,

I installed Registration 0.0.7, and i am trying to get "Enable only for specific groups" feature working - i check it and add the group it should grant to new user. But it does not work - newly made user is still "no group".
Any idea how to solve it?

here is logs:
{"reqId":"8e8dfeb47292ed13469ad1ef344c7aa1","remoteAddr":"111.111.111.111","app":"core","message":"Invalid OCS content returned for app 166053","level":4,"time":"2015-10-14T18:46:10+00:00"}
{"reqId":"8e8dfeb47292ed13469ad1ef344c7aa1","remoteAddr":"111.111.111.111","app":"core","message":"Invalid OCS content returned for app 166038","level":4,"time":"2015-10-14T18:46:10+00:00"}
{"reqId":"8e8dfeb47292ed13469ad1ef344c7aa1","remoteAddr":"111.111.111.111","app":"core","message":"Invalid OCS content returned for app 166049","level":4,"time":"2015-10-14T18:46:10+00:00"}
{"reqId":"8e8dfeb47292ed13469ad1ef344c7aa1","remoteAddr":"111.111.111.111","app":"core","message":"Invalid OCS content returned for app 166050","level":4,"time":"2015-10-14T18:46:10+00:00"}
{"reqId":"8e8dfeb47292ed13469ad1ef344c7aa1","remoteAddr":"111.111.111.111","app":"core","message":"Invalid OCS content returned for app 166056","level":4,"time":"2015-10-14T18:46:11+00:00"}
{"reqId":"8e8dfeb47292ed13469ad1ef344c7aa1","remoteAddr":"111.111.111.111","app":"core","message":"Invalid OCS content returned for app 166051","level":4,"time":"2015-10-14T18:46:11+00:00"}
{"reqId":"8e8dfeb47292ed13469ad1ef344c7aa1","remoteAddr":"111.111.111.111","app":"core","message":"Invalid OCS content returned for app 166052","level":4,"time":"2015-10-14T18:46:11+00:00"}
{"reqId":"8e8dfeb47292ed13469ad1ef344c7aa1","remoteAddr":"111.111.111.111","app":"core","message":"Invalid OCS content returned for app 166059","level":4,"time":"2015-10-14T18:46:11+00:00"}
{"reqId":"8e8dfeb47292ed13469ad1ef344c7aa1","remoteAddr":"111.111.111.111","app":"core","message":"Invalid OCS content returned for app 166055","level":4,"time":"2015-10-14T18:46:12+00:00"}
{"reqId":"8e8dfeb47292ed13469ad1ef344c7aa1","remoteAddr":"111.111.111.111","app":"core","message":"Invalid OCS content returned for app 166054","level":4,"time":"2015-10-14T18:46:12+00:00"}
{"reqId":"94cb7d5ddda8875ab2b004c1c63d710d","remoteAddr":"111.111.111.111","app":"index","message":"Exception: {\"Message\":\"Unable to generate a URL for the named route \\\"registration.register.askEmail\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/path1\\\/lib\\\/private\\\/route\\\/router.php(282): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('registration.re...', Array, false)\\n#1 \\\/path1\\\/lib\\\/private\\\/urlgenerator.php(42): OC\\\\Route\\\\Router->generate('registration.re...', Array)\\n#2 \\\/path1\\\/apps\\\/registration\\\/appinfo\\\/app.php(17): OC\\\\URLGenerator->linkToRoute('registration.re...')\\n#3 \\\/path1\\\/lib\\\/private\\\/app.php(379): require('\\\/parth1...')\\n#4 \\\/path1\\\/settings\\\/ajax\\\/navigationdetect.php(9): OC_App::getAppNavigationEntries('registration')\\n#5 \\\/path1\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/path1...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/path1\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_1413', Array)\\n#8 \\\/path1\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#9 \\\/path1\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/path1\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":4,"time":"2015-10-14T18:46:21+00:00"}
{"reqId":"3f0c7d3ac9fbd8e0f651a9009911b2b3","remoteAddr":"111.111.111.111","app":"PHP","message":"Undefined index: errormsgs at \/path1\/apps\/registration\/templates\/form.php#6","level":3,"time":"2015-10-14T18:47:44+00:00"}
{"reqId":"3f0c7d3ac9fbd8e0f651a9009911b2b3","remoteAddr":"111.111.111.111","app":"PHP","message":"Undefined index: entered_data at \/path1\/apps\/registration\/templates\/form.php#24","level":3,"time":"2015-10-14T18:47:44+00:00"}

**Comment by pellaeon** [comment]
If you want to add newly registered user to a specific group, please do so in the Settings page, you can find Registration section there.
"Enable only for specific groups" feature is provided by ownCloud core for all apps, it has no effect for this Registration app, and may interfere with its working, so please don't enable it for this app.
