### ISSUE TITLE
Publish on apps.owncloud.com

### ISSUE THREAD

**Issue by jancborchardt** [pellaeon/registration#3]
@pellaeon would be cool if you can publish the app on the store at http://apps.owncloud.com

cc @LukasReschke

**Comment by arthuragone** [comment]
Would be really great to see it comming ! Greetings

**Comment by happyreacer** [comment]
nice,... i see you work on time. :+1:

**Comment by happyreacer** [comment]
how is the status?

**Comment by pellaeon** [comment]
Now 2 features left:
[] Admin configuration section, there will be a directive for which group the newly registered users will be added to
[] Check for duplicate emails. You cannot register if there is already a user with that email address.

Recently I got more time, it should be done soon!

**Comment by happyreacer** [comment]
@pellaeon im very happy to hear thees news :-)

**Comment by valueerrorx** [comment]
thx pellaeon!  can't wait to use the finished app :)

you know what other feature would be perfect too?  an automated emailreminder that reminds you to login once in a while or it would delete those selfregistered users after a custom amount of time (5 months no login leads to a reminder (one week ahead) and a deletion)   
 or is this probably something for a different owncloud app?

**Comment by pierreozoux** [comment]
:+1:

**Comment by ldidry** [comment]
@valueerrorx +1 for self-destructing accounts

**Comment by pierreozoux** [comment]
@valueerrorx and @ldidry yes, would be amazing, indeed! (we are working on: http://degooglisons-internet.org/, so it is something we would need :) ) I opened a new issue #9 for that. Let's keep focus on release on app store :)

**Comment by ldidry** [comment]
@pierreozoux I know: @ldidry = framasky :wink:

**Comment by pellaeon** [comment]
Hello everyone, the app is now [published](https://apps.owncloud.com/content/show.php?content=170608) !
Please help me test it! Note that it only supports MySQL/MariaDB backend.

**Comment by pierreozoux** [comment]
:clap:
