### ISSUE TITLE
Default quota for registering users

### ISSUE THREAD

**Issue by intresrl** [pellaeon/registration#33]
Hi.
I like your app very much. Useful!
What about adding default quota definition for registering users DIFFERENT from the "official one".
Please, see the attached image.
The process so becomes:
1. the user register itself. It belongs to a default group with restrictions (maybe: no sharing, quota 0GB) 
2. the admins receive the email notification
3. the admin decide to transfer the new user to a group without restrictions.

Thank you for your job!

![img_1149 00000004](https://cloud.githubusercontent.com/assets/8720648/12599025/c0dfbe20-c48e-11e5-8c70-eac6158d52fc.jpg)

**Comment by pellaeon** [comment]
Admin approval feature is in the works, you can track the progress here: https://github.com/pellaeon/registration/pull/31

**Comment by intresrl** [comment]
Hi.
Thank you for approving my suggestion.
The attached image shows (maybe) a better layout. Just for suggestion.
![img_1149 00000004](https://cloud.githubusercontent.com/assets/8720648/12610736/a4b2eb2c-c4e9-11e5-929d-46d8c96b118c.jpg)

**Comment by pellaeon** [comment]
No, I did not approve your suggestion, I'm just saying what you want is probably admin approval feature, in which no user account would be created at all if the admin does not approve, so no "limiting quota to 0" problem.

**Comment by pellaeon** [comment]
Please take a look at the plan to implement admin approval: https://github.com/pellaeon/registration/issues/2#issuecomment-168125074

**Comment by intresrl** [comment]
Ah, ok.
Sorry for the misunderstanding.




[cid:logo1d076c1]

Daniele Percivaldi

INTRE' S.r.l.
Via Gaslini, 2 - 20900 MONZA (MB) - ITALY
Tel. +39-039-28.45.774 - Fax +39-039-28.40.734
http://www.intre.it e-mail: d.percivaldi@intre.it

Nota informativa:
In ottemperanza della Legge 196/2003 sulla tutela dei dati personali, le informazioni contenute in questo messaggio sono strettamente riservate e sono esclusivamente indirizzate al destinatario indicato (oppure alla persona responsabile di rimetterlo al destinatario), tenendo presente che qualsiasi uso, riproduzione o divulgazione di questo messaggio e' vietata. Nel caso in cui aveste ricevuto questa e-mail per errore, vogliate avvertire il mittente al piu' presto a mezzo posta elettronica e distruggere il presente messaggio.
 Please note:
This email transmission including its attachments, are intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material.  Any views or opinions are solely those of the author and do not necessarily represent those of Intré S.r.l., unless specifically stated.  Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited.   If you received this email in error, please contact the sender and delete the email transmission immediately.

P Please consider the environment before printing this e-mail!

Da: Pellaeon Lin [mailto:notifications@github.com]
Inviato: mercoledì 27 gennaio 2016 11:37
A: pellaeon/registration <registration@noreply.github.com>
Cc: ml_netadmin <netadmin@intre.it>
Oggetto: Re: [registration] Default quota for registering users (#33)


No, I did not approve your suggestion, I'm just saying what you want is probably admin approval feature, in which no user account would be created at all if the admin does not approve, so no "limiting quota to 0" problem.
