### ISSUE TITLE
OC 9.0 support

### ISSUE THREAD

**Issue by ezraholm50** [pellaeon/registration#34]
Hey pellaeon,

Will this great app be updated to be compatible with OC 9.0 + ?

Kind regards

**Comment by pellaeon** [comment]
It should support 9.0 right away, i just need to change the app
requirements xml. I can't just set it to 9.0 because otherwise it wouldn't
pass the approval process.
2016年3月4日 下午9:28於 "Ezra" <notifications@github.com>寫道：

**Comment by ezraholm50** [comment]
Thanks for the quick reply, I'll wait for the edit then. Thanks a lot!

Kind regards

**Comment by pellaeon** [comment]
Updated!
