### ISSUE TITLE
Error while installing/upgrade

### ISSUE THREAD

**Issue by cdamken** [pellaeon/registration#35]
I tried to upgrade from 1.0 to 1.3 version, and was not possible,

I remove the app to try to install it fresh and got:

```
App can't be installed because the version in info.xml/version is not the same as the version reported from the app store
```

**Comment by cdamken** [comment]
I tried to install from the zip 0.1.3 and it hangs in the maintenance mode.

I had to downgrade to 0.1.0

**Comment by pellaeon** [comment]
Sorry, my mistake, I just uploaded the correct zip on app store.

**Comment by cdamken** [comment]
Thanks, I tested it and now the upgrade worked! :+1:  Thanks!
