### ISSUE TITLE
email check regex

### ISSUE THREAD

**Issue by CodeArtha** [pellaeon/registration#40]
Your email validation regex allow for the use of +@+ as address, which is very bad and could break things for anybody that uses the same domain as his owncloud server for a mailserver.

**Comment by pellaeon** [comment]
We rely on the ownCloud `mailer->validateMailAddress` class to validate, so I don't know what you mean by "my email validation regex". And I don't understand how you came to the conclusion.

**Comment by CodeArtha** [comment]
Didn't knew it was oc API used for validation email address. I'll be contacting them directly then.
I've only seen it for your registration app, that in the email field, it let me type +@+ and submit the form. So I thought it must be in your app specificly, but it's true, I should have tested other owncloud email fields before.
