### ISSUE TITLE
Login directly after user creation

### ISSUE THREAD

**Issue by pierreozoux** [pellaeon/registration#43]
Do you think it is feasible? It just reduces one step for the end user :)

**Comment by pellaeon** [comment]
Turns out it was easier than I thought, preliminary results in 6479e16339ec1f3dc82cb90a233d830d572431f1, still a small bug to be fixed.

**Comment by pellaeon** [comment]
Fixed in v0.2.0

**Comment by pierreozoux** [comment]
Amazing! Thanks a lot :)
