### ISSUE TITLE
options under registration buttom

### ISSUE THREAD

**Issue by ezraholm50** [pellaeon/registration#45]
Hey Palleon, 

Still love your app thanks for it! Now I do have a question, I think its better to ask here then at the other apps issue tracker. 

I have this double login without chat line, any idea where to remove the line below the registration button?

Thanks!!!

![deepinscreenshot20160708200937](https://cloud.githubusercontent.com/assets/13510720/16697659/0aacbc96-454b-11e6-8b7f-b0ead181d6d1.png)

**Comment by pellaeon** [comment]
That's probably created by other apps you installed, they seems to be using javascript to append that line, you need to talk to the app developer, I can't do much about it.

**Comment by ezraholm50** [comment]
Yeah that was the guess, will try it somewhere else. Thanks anyway.

Btw when will the app be updated in the appstore to the latest version?

Kind regards,

Ezra

Op za 9 jul. 2016 10:45 schreef Pellaeon Lin <notifications@github.com>:

> That's probably created by other apps you installed, they seems to be
> using javascript to append that line, you need to talk to the app
> developer, I can't do much about it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pellaeon/registration/issues/45#issuecomment-231523728>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AM4oQAtFDDJpp-dI9QhBmP-N5RfKFqUvks5qT1-ngaJpZM4JIRFx>
> .
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by pierreozoux** [comment]
@ezraholm50 can we close the issue?
