### ISSUE TITLE
How to set custom quota for newly registered users

### ISSUE THREAD

**Issue by zawyetun** [pellaeon/registration#46]
Hi Pellaeon,

Thank you for your app, it is very useful for me. And I would like to seek your help on how to set custom quota for newly registered users?

Looking forward your reply, thank you.

**Comment by jorgcastellano** [comment]
I have the same question, as I love the plugins.

**Comment by pellaeon** [comment]
You can set quota for a group, and assign newly registered user to that group in the registration settings.

**Comment by pierreozoux** [comment]
@zawyetun Can we close the issue?
