### ISSUE TITLE
Compatiblility with previous versions.

### ISSUE THREAD

**Issue by cdamken** [pellaeon/registration#48]
Hi @pellaeon,

I see that the code is only for 9.0:
https://github.com/pellaeon/registration/blob/master/appinfo/info.xml#L10

is not anymore compatible with 8.2.X (6,7)

Greetings,

**Comment by pellaeon** [comment]
Yes, I made use of the new Mail API and other new API, so registration requires new version of ownCloud/Nextcloud.
