### ISSUE TITLE
A problem occurred sending email, please contact your administrator.

### ISSUE THREAD

**Issue by argj** [pellaeon/registration#51]
Hi, i have the next error whe new user wants signup:
A problem occurred sending email, please contact your administrator.
PHP 5.6
ownCloud 9.1.2 (stable)

**Comment by argj** [comment]
`exception 'Exception' with message 'Failed recipients: Array ( [0] => hola@hola.com ) ' in /home/www/fshareit.com/fshareit/apps/registration/controller/registercontroller.php:318 Stack trace: #0 /home/www/fshareit.com/fshareit/apps/registration/controller/registercontroller.php(145): OCA\Registration\Controller\RegisterController->sendValidationEmail('GGXK48', 'hola@hola.com') #1 [internal function]: OCA\Registration\Controller\RegisterController->validateEmail() #2 /home/www/fshareit.com/fshareit/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array) #3 /home/www/fshareit.com/fshareit/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Registration\Controller\RegisterController), 'validateEmail') #4 /home/www/fshareit.com/fshareit/lib/private/AppFramework/App.php(99): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Registration\Controller\RegisterController), 'validateEmail') #5 /home/www/fshareit.com/fshareit/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('RegisterControl...', 'validateEmail', Object(OC\AppFramework\DependencyInjection\DIContainer), Array) #6 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array) #7 /home/www/fshareit.com/fshareit/lib/private/Route/Router.php(280): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array) #8 /home/www/fshareit.com/fshareit/lib/base.php(891): OC\Route\Router->match('/apps/registrat...') #9 /home/www/fshareit.com/fshareit/index.php(54): OC::handleRequest() #10 {main}
ownCloud
`

**Comment by pellaeon** [comment]
Please check your mail server log, the problem doesn't look like having anything to do with registration.
Also, test if you can send email properly with "Send test email" in admin settings.

**Comment by jdevstart** [comment]
I'm running into the same issue and tested the "Send test email" per your request.  I have no issues with that per receiving the test e-mail.

Nextcloud 11 (Stable)
Registration v0.2.3
Apache v2.4.18
Redis v3.2.6

**Comment by pellaeon** [comment]
So it seems like your mail server fail intermittently, you can try sending the test email a few more times and I guess it will fail for some times.
This is unlikely registration app's issue since it's using the same function to send emails with NC core. Closing the issue for now, reopen if you're sure registration emails always fail while NC test email always succeed.
