### ISSUE TITLE
Registration does not work with Nextcloud 11

### ISSUE THREAD

**Issue by boubou30** [pellaeon/registration#52]
Hi
Do you think that "registration app" will be updated for nextcloud 11 ?
Thank

**Comment by pellaeon** [comment]
Tested with Nextcloud 11 with no problems, I created a new release v0.2.3 with nextcloud 11 support enabled, download it directly or wait for the app to be approved by Nextcloud app store.

**Comment by boubou30** [comment]
Thanks for these informations.
