### ISSUE TITLE
avalible in nextcloud-appstore

### ISSUE THREAD

**Issue by happyreacer** [pellaeon/registration#53]
@pellaeon 
Thanks for your nice work! I and many other people do it easy to activate a app from the app store. It would be nice if you plugin into the nextcloud appstore  :+1:

**Comment by happyreacer** [comment]
how looks? Is it a problem?

**Comment by pellaeon** [comment]
https://apps.nextcloud.com/apps/registration sorry for the delay, here it is 🎆

**Comment by happyreacer** [comment]
@pellaeon Thanks :+1:
