### ISSUE TITLE
detailed installation

### ISSUE THREAD

**Issue by 00alex** [pellaeon/registration#56]
please describe in detail how and where to throw files and folders

**Comment by pellaeon** [comment]
https://github.com/pellaeon/registration#install

**Comment by 00alex** [comment]
not impossible or anything. box all the files in the apps folder. and that does not work. what am I doing wrong?

**Comment by pellaeon** [comment]
What do you mean by box all the files?
The hierarchy should look like this, also, the folder for this app must take the name `registration`, this is mandated by owncloud:

```
apps/
  registration/
    admin.php
    ....
```

**Comment by 00alex** [comment]
I don't understand. your installation manual is incomprehensible

**Comment by 00alex** [comment]
what am I doing wrong?
1.	Take directory registration-master from archive
2.	Then box in owncloud/apps/
3.	go to the link  /settings/apps
4.	exit from owncloud
no changes
