### ISSUE TITLE
Could not download app registration

### ISSUE THREAD

**Issue by anexit1** [pellaeon/registration#59]
I loaded reg into my nextcloud 11 /apps folder and it does come up on the apps window.  When I click enable I get the following error;

This show in nextcloud logs " Could not download app registration "

Nothing in my log files (apache/php) on the systhe, though.

**Comment by EncryTheGamer** [comment]
@anexit1 im having the same issue, someone help! ;(

**Comment by happyreacer** [comment]
+1 same too,
php 5.6.30
mysql 5.5.54

**Comment by happyreacer** [comment]
okay here are the solution. rename the folder `registration-master` to `registration`
Thats it :+1:

**Comment by anexit1** [comment]
That works, Thanks!
