### ISSUE TITLE
Status of this app?

### ISSUE THREAD

**Issue by pierreozoux** [pellaeon/registration#6]
Hi!

I saw a lot of activity going on here :)

But there is this warning on the first page...
Could I use this app? What are the limitations at the moment?

Thanks a lot for your work :+1:

**Comment by pellaeon** [comment]
Last features are being worked on! please see https://github.com/pellaeon/registration/issues/3#issuecomment-103482041

**Comment by pierreozoux** [comment]
Thanks a lot!
