### ISSUE TITLE
Error	PHP

### ISSUE THREAD

**Issue by NextGenerationcloud** [pellaeon/registration#69]
Hello

Error by registration

When a user gets the e-mail with the link

https://Nextcloudserveradresse/index.php/apps/registration/verify/HF5YCO
Everything is still OK

But when he clicks the link

I get these errors in the cloud

Undefined index: entered_data at /var/www/nextcloud/apps/registration/templates/form.php#24
Undefined index: errormsgs at /var/www/nextcloud/apps/registration/templates/form.php#6

No errors in php.log

??

**Comment by NextGenerationcloud** [comment]
HI 

it may be

Transfer error?
until here everything  ok  The place available
https://Nextcloudserveradresse/index.php/apps/registration/


But this is not
verify/HF5YCO


It would not be so

https://Nextcloudserveradresse/index.php/apps/registration?verify=HF5YCO

**Comment by pellaeon** [comment]
These are simply warnings, you can safely ignore these errors, it won't affect any of the functions.
