### ISSUE TITLE
Disabled admins receives "account created" notification email

### ISSUE THREAD

**Issue by githubos1** [pellaeon/registration#72]
after a successfull registration, all Admins/Groupadmins are beeing informed of the new user beeing registered

BUT  also DISABLED admins are beeing emailed ....   I guess that should not really happen 
----------------------------------
Registration app 0.2.4
Server: 12.0 beta3

Regards,

Oliver

**Comment by pellaeon** [comment]
@githubos1 the issue is now fixed in latest v0.3.1
