### ISSUE TITLE
Does not set user email

### ISSUE THREAD

**Issue by Ganneff** [pellaeon/registration#74]
### Steps to reproduce
1. Install
2. Activate
3. Use

### Expected behaviour
Registered users should have their email configured to the one they used to register with.

### Actual behaviour
Users have no email set

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
12.0.0
Registration 0.2.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
Tarball

**Comment by Ganneff** [comment]
And by now I cant reproduce it anymore, so might have been the moon phase or something. :/

**Comment by memen45** [comment]
I am having the exact same issue. Are you sure nothing has changed now the issue appears to be solved?

**Comment by pellaeon** [comment]
@Ganneff the issue is now fixed in latest v0.3.1
