### ISSUE TITLE
Button is not centered

### ISSUE THREAD

**Issue by AyelGoth** [pellaeon/registration#78]
The registration button on the main page appears off-center. The button should appear centered to match the design of the main page.

**Comment by jsargent7089** [comment]
.button {width: 227px; height: 27px; background-position: right 16px center; background-color: #0085ce; border: 1px solid #0082c9; padding: 10px 20px; color: #fff; font-size: 20px; margin: 5px; border-radius: 3px; min-height: 16px; display: inline-block; font-weight: 600; align-items: flex-start; text-align: center; -webkit-writing-mode: horizontal-tb;}

**Comment by jsargent7089** [comment]
that will fix it

**Comment by GunLab91** [comment]
Hi, i have some problem too button register is not centered, please advise

**Comment by buffcode** [comment]
This is fixed in NextCloud directly with this commit: https://github.com/nextcloud/server/commit/f5aea79bd774f68eac5e2843cb1fe29a3b8f5182

**Comment by pellaeon** [comment]
I haven't tested it myself, but the screenshot from https://github.com/nextcloud/server/pull/6370 looks fine. Note that this had always been a NC/OC issue, there is no way apps could have modify the style of alternative login button.

**Comment by joekerna** [comment]
The issue has reappeared in Nextcloud 18
![grafik](https://user-images.githubusercontent.com/23077594/72730167-182b2980-3b91-11ea-8f4d-98cc90a6983c.png)
