### ISSUE TITLE
Does not set users personal email

### ISSUE THREAD

**Issue by memen45** [pellaeon/registration#81]
### Steps to reproduce
1. Install
2. Activate
3. Use

### Expected behaviour
Registered users should have their email configured to the one they used to register with

### Actual behaviour
Users have no email set in their personal account (i.e. settings > personal >E-mail adres), though on the admin account in 'settings > users' the email addres is visible

### Server configuration
**Operating system**:
Ubuntu Server 16.04

**Web server:**
apache2

**Database:**
mariadb

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

(Note that this appears to be the same issue as #74 , however this is a more specific description)

**Comment by githubos1** [comment]
Hi guys,

I'm seeing exactly the same issue BUT !!!!

1. no e-mail is visible on the newly registered PERSONAL info page
2. no e-mail is visible on the ADMIN USERs Page
BUT BUT BUT 
3. as the newly created user can recover his/her forgotten account password... !! (just tried this)

SO, somewhere in the database the correct e-mail of the registered user must be existing and apparently can be accessed by the system (forgotton password reset), however the e-mail address is not visible to both ADMIN and Registered User.

ONE MORE request... the ADMIN beeing informed by the server of a newly created account and username, should also include the registered Users E-Mail Address for more security and visibility on what'S going on..

Hope this helps,
Oliver

**Comment by githubos1** [comment]
ooops...
now about 15 minutes later (after creation of new account) the users e-mail shows up in ADMIN Users page... buts still not in USERS PERSONAL Info Page..

will recheck in an hour or so..

strange behaviour...

**Comment by pellaeon** [comment]
@githubos1 The issue is now fixed in latest v0.3.1
