### ISSUE TITLE
Typo in German translation

### ISSUE THREAD

**Issue by leonklingele** [pellaeon/registration#83]
```
"To create a new account on %s, just click the following link:" : "Zur Erstellung eines neuen ownCloud Kontos %s, klicken Sie bitte auf den folgenden Link:",
```

which results in `Zur Erstellung eines neuen ownCloud Kontos Nextcloud, klicken` when using Nextcloud.
It should say `"Zur Erstellung eines neuen %s Kontos, klicken Sie bitte auf den folgenden Link:"`

**Comment by leonklingele-work** [comment]
@pellaeon where can I find this project on transifex?

**Comment by pellaeon** [comment]
It's still in the ownCloud team https://www.transifex.com/owncloud-org/owncloud/registration/

**Comment by leonklingele-work** [comment]
[Fixed](https://www.transifex.com/owncloud-org/owncloud/translate/#de_DE/registration/66159510?q=To%20create%20a%20new%20account%20on).
