### ISSUE TITLE
Self-destructing accounts

### ISSUE THREAD

**Issue by pierreozoux** [pellaeon/registration#9]
An automated email reminder that reminds you to login once in a while or it would delete those self registered users after a custom amount of time (5 months no login leads to a reminder (one week ahead) and a deletion)

**Comment by cdamken** [comment]
IMO that does not have to do with the registration.

I you are the administrator you can run an occ command:

https://forum.owncloud.org/viewtopic.php?f=29&t=28527&p=93250&hilit=user%3Alastseen#p93250

**Comment by pierreozoux** [comment]
I was indeed thinking about developing a bash script, but I still think that a proper ownCloud cron would be amazing and a lot cleaner. Speaking with other people I'm not the only one needing this feature.
We probably have someone that will develop it. Hope @pellaeon would accept PR?

Here are the requirements:
In admin area 2 new options:
 - inactivity period to receive warning email (3 months for instance)
 - relax period to login again to avoid account destruction (1 month for instance)

Then, define 2 cron that would:
 - send emails to people where lastlogin > inactivity period
 - delete account where lastlogin > inactivity period + relax period

**Comment by pellaeon** [comment]
Sure, pull requests welcomed!

2016-09-06 0:31 GMT+08:00 Pierre Ozoux <notifications@github.com>:

**Comment by pierreozoux** [comment]
After thinking about it, I'll not delete users account, and let them be, they will just have limited storage.
