### ISSUE TITLE
Update to 0.3.0 fails if there are pending registrations

### ISSUE THREAD

**Issue by AdamBark** [pellaeon/registration#92]
### Steps to reproduce
1. Have some pending registrations
2. Try to update the app

### Expected behaviour
The update should complete

### Actual behaviour
The update fails because it tries to add a new column, "Username", but fails as any current rows will have nulls and this is not allowed.

### Workaround
Drop the oc_registration table; the pending registrations will be lost but they can be requested again.

### Server configuration
**Operating system**:
Host: ubuntu-16.04 running the official nextcloud-fpm, nginx, redis and postgres docker images

**Web server:**
nginx

**Database:**
postgres

**PHP version:**
7.1

**Nextcloud version:** (see Nextcloud admin page)
12.0.1

**Comment by pellaeon** [comment]
It's likely due to the DB schema change introduced in @juliushaertl 's PR.

@juliushaertl Do you have solution for this?

**Comment by AdamBark** [comment]
That's what I suspected. If it is to be done automatically I suspect that either the table should be dropped first or any entries will have to have username set with some value.

The worst case for the former is that the user will have to request registration a second time which isn't that bad but it might be confusing.

**Comment by juliushaertl** [comment]
@pellaeon I'll have a look and see if we can add a migration step for that issue.

**Comment by pellaeon** [comment]
@juliushaertl any update on this ?

**Comment by juliushaertl** [comment]
@pellaeon Ah sorry, totally forgot to check that. Can you assign the issue to me, so i won't forget.

**Comment by pellaeon** [comment]
@juliushaertl somehow I can't assign you, can you assign yourself?

**Comment by juliushaertl** [comment]
@pellaeon @AdamBark A fix is at #104 Sorry for taking so long.

**Comment by AdamBark** [comment]
No problem, thanks for working on this.
