### ISSUE TITLE
Email registration notification shows ownCloud while installation is on Nextcloud

### ISSUE THREAD

**Issue by petrk94** [pellaeon/registration#93]
Hello,

I want to report, that the registration notification email is sending the information that a new account can be created as a ownCloud account, but due its even used by Nextcloud, it would confuse people.
So maybe you can remove it and just keep that a new account got created?

**Comment by pellaeon** [comment]
It should automatically detects whether you are using nextcloud or owncloud and use nextcloud or owncloud in the email, so sounds like you are encountering a bug.

Please fill in a full bug report according to the format of the [issue template](https://github.com/pellaeon/registration/blob/master/issue_template.md). Thanks!
