### ISSUE TITLE
Class registrationService does not exist

### ISSUE THREAD

**Issue by valueerrorx** [pellaeon/registration#95]
Using Ubuntu 16.04
Nextcloud 11.02
Registration 3

downloading and activating the app works fine!

the moment i click on the "register" button that is placed below the login form i get an "internal server error"  

it says to look in the server log for details:

here is the log:
_________________________________________

OCP\AppFramework\QueryException: Could not resolve registrationService! Class registrationService does not exist
/home/student/Webroot/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 117: OC\AppFramework\Utility\SimpleContainer->resolve('registrationSer...')
/home/student/Webroot/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 544: OC\AppFramework\Utility\SimpleContainer->query('registrationSer...')
/home/student/Webroot/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 73: OC\AppFramework\DependencyInjection\DIContainer->query('registrationSer...')
/home/student/Webroot/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 96: OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
/home/student/Webroot/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 117: OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Registratio...')
/home/student/Webroot/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 544: OC\AppFramework\Utility\SimpleContainer->query('OCA\\Registratio...')
/home/student/Webroot/www/owncloud/lib/private/AppFramework/App.php - line 101: OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Registratio...')
/home/student/Webroot/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Registratio...', 'askEmail', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/home/student/Webroot/www/owncloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/home/student/Webroot/www/owncloud/lib/base.php - line 1012: OC\Route\Router->match('/apps/registrat...')
/home/student/Webroot/www/owncloud/index.php - line 48: OC handleRequest()
{main}

**Comment by f763** [comment]
I confirm. I have the same mistake.

**Comment by Mutniks** [comment]
Me too.

**Comment by engle2192** [comment]
Im also getting the same error

**Comment by canphaz** [comment]
Same here unfortunately :-/

**Comment by Raiderpoer** [comment]
Same...

**Comment by engle2192** [comment]
Upgraded to 12.0.2 and now it works like a charm.

**Comment by necrophcodr** [comment]
Ubuntu 14.04.5  
Nextcloud 11.0.4  
Registration 0.3  

The issue persists it appears.

**Comment by pellaeon** [comment]
@juliushaertl I've been looking for the root cause for some days but still have no idea, I think it has something to do with your PR switching to automatic class loading, could you take a look?

**Comment by juliushaertl** [comment]
@pellaeon I've added a patch in #100 that should fix the issue. We were basically missing the namespace entry in appinfo.xml
