### ISSUE TITLE
'Show password' eye-icon doesn't show password

### ISSUE THREAD

**Issue by leonklingele-work** [pellaeon/registration#99]
### Steps to reproduce

Click on the 'Show password' eye-icon to display your password.
![nextcloud-registration-show-password-icon](https://user-images.githubusercontent.com/31063993/30065394-f5fa0d32-9254-11e7-9090-6721488c924e.png)

### Expected result

Field should show your password.

### Actual result

Nothing happens.

Reproduced with Nextcloud 12 (stable) and 13 (beta)

**Comment by pellaeon** [comment]
@leonklingele-work the issue is now fixed in latest v0.3.1

**Comment by danielepercivaldi** [comment]
Sorry, it does not work yet. (oc 9.1.7, php5.5.9, ubuntu 14.04 server lts 64bit)
